### ISSUE TITLE
[BUG] WSL2 openSUSE Tumbleweed zypper packages didn't show up

### ISSUE THREAD

**Issue by justrico** [Macchina-CLI/macchina#284]
**Describe the bug**
openSUSE Tumbleweed on WSL2 didn't display zypper packages.

**To Reproduce**
1. Launch openSUSE Tumbleweed on WSL2
2. Execute macchina

**Expected behavior**
Expect macchina to show up zypper packages.

**Screenshots**
![Snipaste_2023-04-14_12-33-19](https://user-images.githubusercontent.com/52879214/231943409-c6b993eb-1eab-45b4-b8cb-92d4ad97eedc.jpg)

**`macchina --doctor` output**
![Snipaste_2023-04-14_12-42-05](https://user-images.githubusercontent.com/52879214/231943537-942eccd6-f549-4402-ad11-9a61e1340ba7.jpg)

**System Information**
 - Distribution: openSUSE Tumbleweed on WSL2
 - WSL2 version（print from `wsl --version`）
   - WSL version: 1.2.0.0
   - Kernel version: 5.15.90.1
   - WSLg version: 1.0.51
 - Desktop Environment: None
 - Operating System: Windows11 22H2 22621.1555
 - Terminal: Windows Terminal
 - Macchina's version
   - macchina      6.1.8  (f228e72)
   - libmacchina  6.3.5

**Comment by Gobidev** [comment]
Yes, openSUSE uses the `ndb` database backend for RPM, which is why the file `/var/lib/rpm/rpmdb.sqlite` doesn't exist and the package count fails. It might be possible to work around this by switching the backend to `sqlite` manually:
> To change the RPM database backend, you need to edit the /usr/lib/rpm/macros file and set the %_db_backend macro to the desired value (such as sqlite or ndb). [You may also need to rebuild the RPM database using rpmdb --rebuilddb](https://rpm.org/user_doc/db_recovery.html). However, note that changing the RPM database backend is not recommended unless you have a specific reason to do so. It may cause compatibility issues with other tools that rely on the RPM database format.

When trying this on openSUSE Tumbleweed, I got ```warning: invalid %_db_backend: sqlite``` when trying to rebuild the database, so it looks like their build of RPM comes without `sqlite` support.

Like I said in https://github.com/Macchina-CLI/libmacchina/issues/154, the ideal solution would be to somehow get a package count out of the `ndb` database, but this is a lot of work. Spawning an `rpm` process is not really an option for libmacchina, as it takes ~500ms to execute on a modern system.

**Comment by Gobidev** [comment]
This was fixed in https://github.com/Macchina-CLI/libmacchina/pull/159, although the `rpm-devel` package will need to be installed for the detection to work once it is available in macchina.
