### ISSUE TITLE
[BUG] no themes installed and no configs is found

### ISSUE THREAD

**Issue by its-19818942118** [Macchina-CLI/macchina#306]
**Describe the bug**

idk if this is default behaviour but:
using the aur git failed
aur helper failed
installed with cargo
no macchina dir in .config

**To Reproduce**
1.fail insstall with aur and git
2.install with cargo
3.macchina
4.check the themes dir only to see it doesnt exist and inst prepopullated with the necessary files (if that is the default behaviour)

**Expected behavior**

well install goes smoothly. ready to make and edit themes with the macchina dir and polluted with the files

**Screenshots**

**`macchina --doctor` output**
Add a screenshot or copy and paste the output of `--doctor` if an element you're supposed to be seeing isn't showing up.

Let's check your system for errors... Here's a summary:
**```
We've collected 18 readouts, including 3 failed read(s) and 0 read(s) which resulted in a warning.
Readout "OperatingSystem" failed with message: This metric is not available on this platform or is not yet implemented by libmacchina.
Readout "WindowManager" failed with message: Unknown window manager.
Readout "LocalIP" failed with message: Unable to get local IPv4 address.
```**
**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: [`EndeavourOS`]
 - Desktop Environment [Hyprland]
 - Operating System [Linux]
 - Terminal [Kitty]
 - Macchina's version [6.1.8]

**Comment by grtcdr** [comment]
How did you install it from the AUR? Can you attach the error output?

macchina does not create a `config.toml` nor any themes for you by default. You should assemble it yourself by reading the manual or manually download and customize the provided configuration and themes found in the repository.

I'm closing the issue because it's a non-issue from our perspective. If you're still having issues with downloading macchina from the AUR, please open another issue or rename this one to better fit the description.
